### ISSUE TITLE
Flickering of `<a>` (link) tags with `transition: all` 

### ISSUE THREAD

**Issue by sakkamade** [birchill/10ten-ja-reader#724]
Active Rikaichamp (however it's named now) causes a flickering transition of `<a>` html-tag.

Tested on Firefox 91.0 (64-bit)
Rikaichamp 1.2.1 (Although was experiencing this for quite a while—month since I noticed? Had no idea that this add-on is at fault.) 
Arch Linux.

<details><summary>Test document</summary>

```html
<!DOCTYPE html>
<html>
<head>
<style>
.test {
    border: 1px solid #ddd;
    -webkit-transition: all 0.2s ease-in-out;
    -moz-transition: all 0.2s ease-in-out;
    -o-transition: all 0.2s ease-in-out;
    transition: all 0.2s ease-in-out;
}

.test:hover {
    border-color: #000;
}
</style>
</head>
<body>

<a class="test" href="#">This is a link.</a>

</body>
</html>
```
</details>

P.s. `transition: border-color` solves it.

**Comment by sakkamade** [comment]
> for quite a while 

I've noted it on July 13th, if this would be of any help.

**Comment by birtles** [comment]
This is quite odd yet #723 appears to report the same thing. I think what's happening is 10ten's mousemove handling is flushing style.

**Comment by birtles** [comment]
I still need to dig into this further, but at a quick glance, it looks like 10ten does indeed flush style in its mousemove handling. However, as far as I can tell, it has been doing that for years. I wonder if something changed in the user agent stylesheet for Arch Linux that simply makes it more noticeable now.

**Comment by sakkamade** [comment]
> This is quite odd yet #723 appears to report the same thing.

I cannot reproduce it. However I remember seeing something similar as well

**Comment by sakkamade** [comment]
This has nothing to do with Arch Linux.

I have tested it now with Firefox 78.0 (64 bit) on Windows 10—exactly the same flickering.

**Comment by birtles** [comment]
Right, I can reproduce it on Windows too.

I'm just trying to make sense of the fact that I received two bug reports for roughly the same issue within hours of each other: one from an Arch Linux user and one from someone browsing the Arch Linux download page!

The good news is I can't reproduce on a commit on 1 Jan 2021 so I am currently bisecting the regression range. So far it looks like it goes back pretty far -- somewhere between the start of April and the end of May.

**Comment by sakkamade** [comment]
> I'm just trying to make sense of the fact that I received two bug reports for roughly the same issue within hours of each other

Well, coincidence?

I have already said that
> Although I was experiencing this for quite a while—month since I noticed? I had no idea that this add-on is at fault

**Comment by birtles** [comment]
Unfortunately it looks like aa8209ba7ffeaf8e7475 is to blame.

That patch makes us toggle the `pointer-events` property of link elements so we can see if there is actually text underneath them. I guess it's applying that behaviour in this test case even when it needn't and probably needs to be a bit smarter.

**Comment by birtles** [comment]
Fixed by 1dead877556a7e8edb0b2af56720b16de9552e6d

**Comment by birtles** [comment]
Version 1.2.2 was released yesterday so this should be fixed now.

**Comment by sakkamade** [comment]
@birtles, Thank you for notification! 

Well, what can I say, it _is_ better now.

The behaviour is still present on my side, for example, when I quickly move the cursor though such page:

<details><summary>Document Body</summary>

```html
<body>
<a class="test" href="#">This is a link.</a><br>

<a class="test" href="#">This is a link.</a><br>

<a class="test" href="#">This is a link.</a><br>

<a class="test" href="#">This is a link.</a><br>

<a class="test" href="#">This is a link.</a><br>

<a class="test" href="#">This is a link.</a><br>

<a class="test" href="#">This is a link.</a><br>

<a class="test" href="#">This is a link.</a><br>

<a class="test" href="#">This is a link.</a><br>
</body>
```

</details>

**Comment by birtles** [comment]
@sakkamade Thank you for checking!

I'm having trouble noticing any difference with that test case between when the add-on is enabled vs when it is not.

I've confirmed that in that test case we're not triggering the "covering link" behavior so it must be a separate issue. If there's some more reliable means to reproduce it then I'd be glad to hear it!

**Comment by sakkamade** [comment]
> If there's some more reliable means to reproduce it then I'd be glad to hear it!

I wonder if there are _more_ reliable.


https://user-images.githubusercontent.com/62730422/130287498-b2d60d65-47fc-42d5-982c-cc57ae3753fa.mp4

**Comment by sakkamade** [comment]
@birtles, So can it be reopened, then?

**Comment by birtles** [comment]
Hi @sakkamade, I had a look at the new test case and it looks like those links are stacked so close together that they end up overlapping each other, triggering the "link uncovering" behavior that causes flicker. If you set `line-height: 2` on the body, for example, so that they are no longer overlapping, the flicker will disappear. This also explains why it only happens going downwards and only when moving quickly (because they only overlap while the above element is transitioning).

I think the flicker is an unfortunate but necessary side effect of the (very useful) link uncovering behavior. It could be optimized further but I don't think it's worth it. Please let me know if there is specific content in the wild where this is causing problems and I'll be happy to look into it.

**Comment by sakkamade** [comment]
>  (...) it looks like those links are stacked so close together that they end up overlapping each other (...)

Right, this is certainly true, in this case,
 but sadly, sometimes  I still do see this behaviour in practice (sometimes one time in hundred hovers, sometimes two in ten), with links of visually proper margins (not overlapping).

I am unable to replicate the circumstances for reliable reproduction with original content, but I am mostly certain that it is caused by something similar to this:

<details><summary><code>HTML test</code></summary>

```html
<!DOCTYPE html>
<html>
<head>
<style>
body { line-height: 60px; }

.test {
    border: 1px solid #ddd;
    transition: all 0.2s ease-in-out;
    padding: 10px;
    display: block;
}

.test:hover {
    border-color: #000;
    box-shadow: 0 1px 4px rgba(0, 105, 214, 0.25);
}
.test div { height: 40px; }
</style>
</head>
<body>

<a class="test" href="#" style="">
<div class="test2">
<p class="">test line</p>
<p class="">test overlap line</p>
</div>
</a>

</body>
</html>
```
</details>

Hovering the overlapped `<div>` and not the `<a>` (link) is also a source of flicker.

What are your thoughts regarding this one?

**Comment by birtles** [comment]
Thanks for following up on this and providing a test case too! I'm more than happy to look into it when there's some real content that's significantly affected by it, but until then I'm afraid I'm not convinced it's worth spending time on. I'm happy to review a PR though if you'd like to look into it further.

**Comment by sakkamade** [comment]
> real content that's significantly affected by it

So far I've seen none.
> I'm happy to review a PR though if you'd like to look into it further.

No, [this](https://github.com/birchill/10ten-ja-reader/issues/724#issuecomment-904294998) is as far as I will.

Oh well. Thank you.
